Api
Juniyegorov/HealthMonitoring pull request #1
Opened 2021-11-16 12:55 UTC by Juniyegorov

2021-11-17 08:07 UTC, Lsdenis requested changes
Фронт не смотрел, остальное надо поправить

2021-11-17 08:07 UTC, Lsdenis commented on HealthMonitoring.Presentation.WebAPI/Controllers/AccountController.cs
> +            Action<string> action = AddMessageEror;
ой ей, делегаты не надо пробрасывать
надо просто возвращать результат из метода

2021-11-17 08:07 UTC, Lsdenis commented on HealthMonitoring.Presentation.WebAPI/Controllers/AccountController.cs
> +            if (_message == "Registration successful")
_message поле нельзя так ипользовать, необходимо использоваться возвращаемый результат

2021-11-17 08:07 UTC, Lsdenis commented on HealthMonitoring.Presentation.WebAPI/Controllers/AccountController.cs
> +            if (_message == "Registration successful")
сравнение результата по строке тоже очень-очень плохо, лучше использовать бул или енама

2021-11-17 08:07 UTC, Lsdenis commented on HealthMonitoring.Presentation.WebAPI/Controllers/AccountController.cs
> +        private void AddMessageEror(string message)
как делегат использовать не очень хорошо + отступ

2021-11-17 08:07 UTC, Lsdenis commented on HealthMonitoring.Presentation.WebAPI/Controllers/ActivityController.cs
> +        private IUserServices _userServices;
отступ

2021-11-17 08:07 UTC, Lsdenis commented on HealthMonitoring.Presentation.WebAPI/Controllers/AccountController.cs
> +        private string _message;
отступ

2021-11-17 08:07 UTC, Lsdenis commented on HealthMonitoring.Presentation.WebAPI/Controllers/ActivityController.cs
> +            var exercises = _exercisesService.GetAllExercises();
что за пробелы в конце?

2021-11-17 08:07 UTC, Lsdenis commented on HealthMonitoring.Presentation.WebAPI/Controllers/DishController.cs
> +    [ApiController]
зачем нужен атрибут ApiController?

2021-11-17 08:07 UTC, Lsdenis commented on HealthMonitoring.Presentation.WebAPI/Models/EatenDish.cs
> +        public string Name { get; set; }
отступы при свойствах и атрибутах

2021-11-17 13:31 UTC, Juniyegorov commented on HealthMonitoring.Presentation.WebAPI/Controllers/AccountController.cs
> +            Action<string> action = AddMessageEror;
Исправил

2021-11-17 13:31 UTC, Juniyegorov commented on HealthMonitoring.Presentation.WebAPI/Controllers/AccountController.cs
> +            if (_message == "Registration successful")
Исправил

2021-11-17 13:31 UTC, Juniyegorov commented on HealthMonitoring.Presentation.WebAPI/Controllers/AccountController.cs
> +        private void AddMessageEror(string message)
Исправил

2021-11-17 13:31 UTC, Juniyegorov commented on HealthMonitoring.Presentation.WebAPI/Controllers/ActivityController.cs
> +        private IUserServices _userServices;
Исправил

2021-11-17 13:31 UTC, Juniyegorov commented on HealthMonitoring.Presentation.WebAPI/Controllers/AccountController.cs
> +        private string _message;
Исправил

2021-11-17 13:31 UTC, Juniyegorov commented on HealthMonitoring.Presentation.WebAPI/Controllers/ActivityController.cs
> +            var exercises = _exercisesService.GetAllExercises();
Убрал)

2021-11-17 13:36 UTC, Juniyegorov commented on HealthMonitoring.Presentation.WebAPI/Controllers/DishController.cs
> +    [ApiController]
Позволяет добавить к контроллеру некоторую дополнительную функциональность (автоматические ответы Http 400,  маршрутизация по атрибутам, вывод параметра источника привязки ([FromBody], [FromForm], [FromHeader], [FromQuery], [FromRoute], [FromServices]))

2021-11-17 13:36 UTC, Juniyegorov commented on HealthMonitoring.Presentation.WebAPI/Models/EatenDish.cs
> +        public string Name { get; set; }
Добавил

2021-11-18 12:17 UTC, Lsdenis approved these changes

2021-11-18 12:17 UTC, Lsdenis commented on HealthMonitoring.DataAccessLayer/Repositories/UserRepository.cs
>          }
пробела нет

2021-11-18 12:24 UTC, merged